// app/layout.tsx (or wherever your RootLayout is)
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Appbar from "./components/Appbar";
import Navbar from "./components/Appbar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Persevex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
